### ISSUE TITLE
Hand rotation

### ISSUE THREAD

**Issue by TobiasWa** [ritchielozada/HoloLensHandTracking#1]
There exists a function which is called "handOrientatation" but I can't access it. Do you think it is possible to also have a rotation of the hand instead of just having the position?

**Comment by ritchielozada** [comment]
When I wrote this sample a while back,  Rotation (Orientation) data is not being returned.
I'm working on a new sample on Unity 2017.2 (Beta) that uses the new UnityEngine.XR.WSA.Input namespace that unifies hand and controller tracking in InputManager.   The Immersive Headset controllers reports position and rotation.   I have not tested hand tracking recently for HoloLens but I think it's still limited to position only.   I'm waiting for the Mixed Reality Controllers for the Immersive headsets to be more available to developers so I can validate and release the sample.

**Comment by ritchielozada** [comment]
I included the TryGetRotation() in the script for the eventual Motion Controller sample which returns rotation tracking.  Still not an option for the HoloLens Hand Input as writing.
